apiVersion: v1
kind: Namespace
metadata:
  name: hpe-pov-app
  
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI4MDg0LW5leHVzLWF3cWJhYm50LnByb2RxYS5vcHNlcmEuaW8iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiYUFCRE84dXU2ZyIsImVtYWlsIjoibmF3YXpAb3BzZXJhLmlvIiwiYXV0aCI6IllXUnRhVzQ2WVVGQ1JFODRkWFUyWnc9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-nexus
  namespace: hpe-pov-app
type: kubernetes.io/dockerconfigjson
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpe-pov-app
  namespace: hpe-pov-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: docker-nexus
      containers:
        - name: back-end
          image: 8084-nexus-awqbabnt.prodqa.opsera.io/hpe-pov-docker:11adc57a88115d40cb2210a96019ca391561bc0e
          ports:
            - containerPort: 8072
          env:
          - name: DOCKER_ENV
            value: "dev"

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: argo-demo
  name: hpe-pov-app
  namespace: hpe-pov-app
spec:
  ports:
  - name: http
    port: 8072
    protocol: TCP
    targetPort: http
  selector:
    app: web
  sessionAffinity: None
  type: NodePort

---
