apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
namespace: argokustomize
images:
- name: the-my-app
  newName: 792373136340.dkr.ecr.us-east-1.amazonaws.com/nlpargoecrrepo
  newTag: "18"
