apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
namespace: argocd
images:
- name: the-my-app
  newName: 440953937617.dkr.ecr.us-east-2.amazonaws.com/python-example
  newTag: 2f26c9adab8810ffc171b4807e6ca32f69a12a13
