apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJvcHNlcmFkZXYuamZyb2cuaW8iOnsidXNlcm5hbWUiOiJzcmluaXZhc2FuQG9wc2VyYS5pbyIsInBhc3N3b3JkIjoiT3BzZXJhQDEyMyIsImVtYWlsIjoicHVydXNob3RoYW1hbkBvcHNlcmEuaW8iLCJhdXRoIjoiYzNKcGJtbDJZWE5oYmtCdmNITmxjbUV1YVc4NlQzQnpaWEpoUURFeU13PT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-jfrog
  namespace: argocd
type: kubernetes.io/dockerconfigjson
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: docker-jfrog
      containers:
        - name: back-end
          image: opseratest.jfrog.io/opsera-docker-repo:00d97cd5a39abce64000df9db4645d8c52708de6
          imagePullPolicy: Always
          ports:
            - containerPort: 8072
          env:
          - name: DOCKER_ENV
            value: "kubernetes"

---
